### ISSUE TITLE
Feature request | Holdable sprint

### ISSUE THREAD

**Issue by K0NR4D1U5** [RunwayStudios/After-hours-issueboard#50] opened 2022-01-21 22:51 UTC
Make sprint button holdable

**Comment by K0NR4D1U5** [comment] 2022-01-25 15:28
Doesnt work at all when pressing sprint key first and then "W"

**Comment by SwipSwup** [comment] 2022-01-25 20:10
Couldn't reproduce behaviour. Without further information i won't be able to fix the issue. Closing it for now

**Closed by SwipSwup** 2022-01-25 20:10 UTC
Labels: feature request
